server:
  port: 10001

spring:
  application:
    name: auth-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: ps_auth
    password: ps_auth
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/postgres
    user: ps_auth
    password: ps_auth

security:
  jwt:
    keystore:
      password: password
      alias: 1
      filename: classpath:pv-keystore.p12


logging:
  level:
    root: info
    web: info
    sql: info