server:
  port: 9000

spring:
  application:
    name: reference-service
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:pv-public.pem
          iss: 1
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: ps_reference
    password: ps_reference
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/postgres
    user: ps_reference
    password: ps_reference


core:
  config:
    security:
      security-props:
        path: classpath:application-access.yaml