security-props:
  spaceMatchers:
    - method: GET
      path: /references/items/**
      access: REFERENCE_ITEM_READ

  matchers:
    - method: GET
      path: /references/items/**
      access: REFERENCE_ITEM_READ

  ignoring:

  basic-matchers:
    - method: GET
      path: /references/items
      username: demo-client
      password: demo-client
