server:
  port: 9004

spring:
  application:
    name: git-service
  web:
    locale: ru
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:pv-public.pem
          iss: 1
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: ps_git
    password: ps_git
  flyway:
    url: jdbc:postgresql://localhost:5432/postgres
    user: ps_git
    password: ps_git

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      bootstrap-servers: localhost:9092
      transaction-id-prefix: ${spring.application.name}-tx.
      properties.spring.json.add.type.headers: true
      ack: -1
    consumer:
      bootstrap-servers: localhost:9092
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
      max-poll-records: 2
      properties:
        isolation.level: read_committed
        spring.json.trusted.packages: 'com.kapitonau.projectstudio.event'
    listener:
      ack-mode: manual_immediate
    properties:
      max.block.ms: 7000

api:
  reference-service:
    url: http://localhost:9000
  project-service:
    url: http://localhost:9001

core:
  config:
    security:
      security-props:
        path: classpath:application-access.yaml

kafka:
  topic:
    git-repository-add-event:
      name: git-repository-add
      groupId: git-repository-add-event_groupId
      sleepTimeMs: 60000